[build-system]
requires = ["setuptools>=45", "wheel", "build"]
build-backend = "setuptools.build_meta"

[project]
name = "common"
version = "0.1"

[tool.setuptools.packages.find]
where = ["."]
include = ["common*"]